# Generated by Django 6.0.4 on 2026-04-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_customer_first_name_remove_customer_last_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
